// src/components/MessageList/Attachment.jsx
import style from './style';

const Attachment = props => {
	return (
		<div className={style.attachment}>
			{
				/\.(jpe?g|png|gif)$/.test(props.attachment.url.toLowerCase()) ?
					<img
						width={props.attachment.width || null}
						height={props.attachment.height || null}
						src={props.attachment.url}
						className={style['attachment-image']}
					/> :
					<div className={style['attachment-file']}>
						<a href={props.attachment.url}>{props.attachment.name}</a>
						<span className={style['attachment-size']}>{props.attachment.size} bytes</span>
					</div>
			}

		</div>
	);
};

export default Attachment;

// src/components/Attachment.vue
<template>
	<div>
		<img
			v-if="isImage()"
			:src="attachment.url"
			class="attachment"
		>
		<div
			v-else
			class="attachment"
		>
			<a :href="attachment.url">{{ attachment.name }}</a>
			<span>{{ attachment.size }} bytes</span>
		</div>
	</div>
</template>

<script>
export default {
	name: 'Attachment',
	props: {
		'attachment': {
			type: Object,
			required: true
		}
	},
	data: function () {
		return {};
	},
	methods: {
		isImage () {
			const fileExtension = this.attachment.url.split('.').slice(-1)[0].toLowerCase();

			return (
				fileExtension === 'png' ||
				fileExtension === 'jpeg' ||
				fileExtension === 'jpg' ||
				fileExtension === 'gif'
			);
		}
	}
};
</script>
